drop table endereco if exists; 

drop table evento if exists; 

drop table grupo if exists; 

drop table grupo_integrante if exists; 

drop table integrante if exists; 

drop table noticia if exists; 

drop table topico_noticia if exists; 

create table endereco (
 id bigint generated by default as identity,
  cep varchar(255),
  cidade varchar(255),
  complemento varchar(255),
  logradouro varchar(255),
  numero varchar(255),
  uf varchar(255),
  primary key (id)
); 

create table evento (
 id bigint generated by default as identity,
  data time,
  descricao varchar(255),
  lotacao_maxima integer,
  motivo varchar(255),
  valor decimal(19,2),
  endereco_id bigint,
  grupo_id bigint,
  primary key (id)
); 

create table grupo (
 id bigint generated by default as identity,
  igreja varchar(255),
  nome varchar(255),
  primary key (id)
); 

create table grupo_integrante (
 grupo_id bigint not null,
  integrante_id bigint not null
); 

create table integrante (
 id bigint generated by default as identity,
  cadastro_efetivado boolean,
  celular varchar(255),
  cpf varchar(255),
  data_nascimento date,
  email varchar(255),
  membro_da_igreja boolean,
  membro_de_outra_igreja boolean,
  nome varchar(255),
  nome_da_outra_igreja varchar(255),
  senha varchar(255),
  sexo varchar(255),
  primary key (id)
); 

create table noticia (
 id bigint generated by default as identity,
  corpo varchar(255),
  titulo varchar(255),
  grupo_id bigint,
  primary key (id)
); 

create table topico_noticia (
 noticia_id bigint not null,
  topico varchar(255) not null
); 

alter table evento 
 add constraint FKqd0alhw4xw95c617h4kgil7qs 
 foreign key (endereco_id) 
 references endereco; 

alter table evento 
 add constraint FKejsn618nl0f3de2ptjrnrh0aq 
 foreign key (grupo_id) 
 references grupo; 

alter table grupo_integrante 
 add constraint FKll5l17672k69q3nd3drcniyv7 
 foreign key (integrante_id) 
 references integrante; 

alter table grupo_integrante 
 add constraint FK9kr7iurbfdihqyxhm04cb1j3f 
 foreign key (grupo_id) 
 references grupo; 

alter table noticia 
 add constraint FK5x8upyj0imhvfs6i69ow6efdg 
 foreign key (grupo_id) 
 references grupo; 

alter table topico_noticia 
 add constraint FKea50ksdyobcykn4extm18m3hk 
 foreign key (noticia_id) 
 references noticia;